uninteresting_terms = ['Humans', 'Male', 'Female', ]

groupterm = {
    "administration & dosage" : "ADMINISTRATION",
    "administration, oral" : "ADMINISTRATION",
    "adolescent" : "AGE",
    "adult" : "AGE",
    "age factors" : "AGE",
    "aged" : "AGE",
    "aged, 80 and over" : "AGE",
    "child" : "AGE",
    "child, preschool" : "AGE",
    "infant" : "AGE",
    "infant mortality" : "AGE",
    "infant, newborn" : "AGE",
    "infant, newborn, diseases" : "AGE",
    "infant, premature" : "AGE",
    "middle aged" : "AGE",
    "gestational age" : "AGE",
    "animals" : "ANIMAL_MODELS",
    "mice" : "ANIMAL_MODELS",
    "rabbits" : "ANIMAL_MODELS",
    "antibodies" : "ANTIBODY",
    "antibodies, viral" : "ANTIBODY",
    "antibody formation" : "ANTIBODY",
    "antibody specificity" : "ANTIBODY",
    "antigen-antibody reactions" : "ANTIBODY",
    "fluorescent antibody technique" : "ANTIBODY",
    "arsenic" : "ARSENIC",
    "arsenicals" : "ARSENIC",
    "arthritis" : "ARTHRITIS",
    "arthritis, infectious" : "ARTHRITIS",
    "arthritis, rheumatoid" : "ARTHRITIS",
    "bacteria" : "BACTERIA",
    "bacterial infections" : "BACTERIA",
    "bacterial proteins" : "BACTERIA",
    "bacterial vaccines" : "BACTERIA",
    "bacteriological techniques" : "BACTERIA",
    "dna, bacterial" : "BACTERIA",
    "anti-bacterial agents" : "BACTERIA",
    "antigens, bacterial" : "BACTERIA",
    "endocarditis, bacterial" : "BACTERIA",
    "antibodies, bacterial" : "BACTERIA",
    "hemagglutination tests" : "BLOOD",
    "hemoglobinuria, paroxysmal" : "BLOOD",
    "agglutination tests" : "BLOOD",
    "blood" : "BLOOD",
    "blood banks" : "BLOOD",
    "blood donors" : "BLOOD",
    "blood proteins" : "BLOOD",
    "blood supply" : "BLOOD",
    "blood transfusion" : "BLOOD",
    "anemia" : "BLOOD",
    "leukocyte count" : "BLOOD",
    "leukocytes" : "BLOOD",
    "bone and bones" : "BONE",
    "bone diseases" : "BONE",
    "brain" : "BRAIN",
    "brain diseases" : "BRAIN",
    "brain neoplasms" : "BRAIN",
    "cerebral angiography" : "BRAIN",
    "cerebrospinal fluid" : "BRAIN",
    "cerebrospinal fluid proteins" : "BRAIN",
    "cerebrovascular disorders" : "BRAIN",
    "encephalitis" : "BRAIN",
    "electroencephalography" : "BRAIN",
    "mental disorders" : "BRAIN",
    "electrocardiography" : "CARDIO",
    "heart diseases" : "CARDIO",
    "heart valve diseases" : "CARDIO",
    "heart defects, congenital" : "CARDIO",
    "hypertension" : "CARDIO",
    "syphilis, cardiovascular" : "CARDIO",
    "aorta" : "CARDIO",
    "aorta, thoracic" : "CARDIO",
    "aortic aneurysm" : "CARDIO",
    "aortic diseases" : "CARDIO",
    "aortic rupture" : "CARDIO",
    "aortic valve" : "CARDIO",
    "aortic valve insufficiency" : "CARDIO",
    "aortitis" : "CARDIO",
    "aortography" : "CARDIO",
    "cardiolipins" : "CARDIO",
    "cardiovascular diseases" : "CARDIO",
    "coronary disease" : "CARDIO",
    "myocardial infarction" : "CARDIO",
    "clinical" : "CLINIC",
    "clinical laboratory techniques" : "CLINIC",
    "clinical trials as topic" : "CLINIC",
    "hospitalization" : "CLINIC",
    "hospitals" : "CLINIC",
    "health services" : "CLINIC",
    "medical records" : "CLINIC",
    "outpatient clinics, hospital" : "CLINIC",
    "ambulatory care" : "CLINIC",
    "ambulatory care facilities" : "CLINIC",
    "congenital" : "CONGENITAL",
    "congenital abnormalities" : "CONGENITAL",
    "toxoplasmosis, congenital" : "CONGENITAL",
    "condoms" : "CONTRACEPTION",
    "contraception" : "CONTRACEPTION",
    "continental population groups" : "DEMOGRAPHY",
    "demography" : "DEMOGRAPHY",
    "developing countries" : "DEMOGRAPHY",
    "emigration and immigration" : "DEMOGRAPHY",
    "transients and migrants" : "DEMOGRAPHY",
    "travel" : "DEMOGRAPHY",
    "urban population" : "DEMOGRAPHY",
    "population surveillance" : "DEMOGRAPHY",
    "rural population" : "DEMOGRAPHY",
    "diabetes complications" : "DIABETES",
    "diabetes mellitus" : "DIABETES",
    "diagnosis" : "DIAGNOSIS",
    "diagnosis, differential" : "DIAGNOSIS",
    "diagnostic errors" : "DIAGNOSIS",
    "diagnostic tests, routine" : "DIAGNOSIS",
    "parasitic diseases" : "DISEASE",
    "acute disease" : "DISEASE",
    "anus diseases" : "DISEASE",
    "labyrinth diseases" : "DISEASE",
    "disease" : "DISEASE",
    "disease management" : "DISEASE",
    "disease models, animal" : "DISEASE",
    "disease outbreaks" : "DISEASE",
    "epidemiologic methods" : "DISEASE",
    "epidemiology" : "DISEASE",
    "joint diseases" : "DISEASE",
    "dose-response relationship, drug" : "DRUG",
    "drug administration schedule" : "DRUG",
    "drug effects" : "DRUG",
    "drug eruptions" : "DRUG",
    "drug hypersensitivity" : "DRUG",
    "drug resistance, microbial" : "DRUG",
    "drug therapy" : "DRUG",
    "drug therapy, combination" : "DRUG",
    "deafness" : "EAR",
    "ear, inner" : "EAR",
    "hearing loss, sensorineural" : "EAR",
    "patient education as topic" : "EDUCATION",
    "education" : "EDUCATION",
    "educational status" : "EDUCATION",
    "health education" : "EDUCATION",
    "sex education" : "EDUCATION",
    "ethnic groups" : "ETHNIC",
    "ethnology" : "ETHNIC",
    "european continental ancestry group" : "ETHNIC",
    "african americans" : "ETHNIC",
    "african continental ancestry group" : "ETHNIC",
    "attitude to health" : "HEALTH",
    "delivery of health care" : "HEALTH",
    "health" : "HEALTH",
    "health surveys" : "HEALTH",
    "primary health care" : "HEALTH",
    "public health" : "HEALTH",
    "urban health" : "HEALTH",
    "hepatitis" : "HEPATITIS",
    "hepatitis a" : "HEPATITIS",
    "hepatitis b" : "HEPATITIS",
    "hepatitis b antibodies" : "HEPATITIS",
    "hepatitis b surface antigens" : "HEPATITIS",
    "hepatitis c" : "HEPATITIS",
    "hepatitis, viral, human" : "HEPATITIS",
    "history" : "HISTORY",
    "history, 15th century" : "HISTORY",
    "history, 16th century" : "HISTORY",
    "history, 17th century" : "HISTORY",
    "history, 18th century" : "HISTORY",
    "history, 19th century" : "HISTORY",
    "history, 20th century" : "HISTORY",
    "history, ancient" : "HISTORY",
    "history, medieval" : "HISTORY",
    "history, modern 1601-" : "HISTORY",
    "hiv antibodies" : "HIV-AIDS",
    "hiv infections" : "HIV-AIDS",
    "hiv seropositivity" : "HIV-AIDS",
    "acquired immunodeficiency syndrome" : "HIV-AIDS",
    "immunity" : "INMUNE",
    "immunity, cellular" : "INMUNE",
    "immunization" : "INMUNE",
    "immunoenzyme techniques" : "INMUNE",
    "immunoglobulin a" : "INMUNOLOGY",
    "immunoglobulin g" : "INMUNOLOGY",
    "immunoglobulin m" : "INMUNOLOGY",
    "immunoglobulins" : "INMUNOLOGY",
    "immunology" : "INMUNOLOGY",
    "centers for disease control and prevention (u.s.)" : "INSTITUTION",
    "organization & administration" : "INSTITUTION",
    "world health organization" : "INSTITUTION",
    "united states public health service" : "INSTITUTION",
    "nephrotic syndrome" : "KIDNEY",
    "kidney" : "KIDNEY",
    "kidney diseases" : "KIDNEY",
    "liver" : "LIVER",
    "liver cirrhosis" : "LIVER",
    "liver diseases" : "LIVER",
    "liver function tests" : "LIVER",
    "lung" : "LUNG",
    "lung diseases" : "LUNG",
    "lymph nodes" : "LYMPH",
    "lymphadenitis" : "LYMPH",
    "lymphatic diseases" : "LYMPH",
    "lymphocyte activation" : "LYMPH",
    "lymphocytes" : "LYMPH",
    "lymphogranuloma venereum" : "LYMPH",
    "lymphoma" : "LYMPH",
    "optic atrophy" : "OPTIC",
    "optic nerve" : "OPTIC",
    "optic neuritis" : "OPTIC",
    "vision disorders" : "OPTIC",
    "visual acuity" : "OPTIC",
    "blindness" : "OPTIC",
    "eye infections, bacterial" : "OPTIC",
    "eye" : "OPTIC",
    "eye diseases" : "OPTIC",
    "fundus oculi" : "OPTIC",
    "chorioretinitis" : "OPTIC",
    "retinitis" : "OPTIC",
    "pupil" : "OPTIC",
    "penicillin g" : "PENICILLIN",
    "penicillin g benzathine" : "PENICILLIN",
    "penicillin g procaine" : "PENICILLIN",
    "penicillin resistance" : "PENICILLIN",
    "penicillins" : "PENICILLIN",
    "new york" : "PLACES",
    "new york city" : "PLACES",
    "nigeria" : "PLACES",
    "north america" : "PLACES",
    "norway" : "PLACES",
    "netherlands" : "PLACES",
    "poland" : "PLACES",
    "russia" : "PLACES",
    "scotland" : "PLACES",
    "south africa" : "PLACES",
    "spain" : "PLACES",
    "sweden" : "PLACES",
    "switzerland" : "PLACES",
    "tanzania" : "PLACES",
    "texas" : "PLACES",
    "uganda" : "PLACES",
    "united states" : "PLACES",
    "ussr" : "PLACES",
    "africa" : "PLACES",
    "alabama" : "PLACES",
    "asia" : "PLACES",
    "australia" : "PLACES",
    "austria" : "PLACES",
    "brazil" : "PLACES",
    "california" : "PLACES",
    "canada" : "PLACES",
    "china" : "PLACES",
    "denmark" : "PLACES",
    "england" : "PLACES",
    "ethiopia" : "PLACES",
    "europe" : "PLACES",
    "france" : "PLACES",
    "germany" : "PLACES",
    "india" : "PLACES",
    "italy" : "PLACES",
    "jamaica" : "PLACES",
    "japan" : "PLACES",
    "kenya" : "PLACES",
    "london" : "PLACES",
    "mexico" : "PLACES",
    "great britain" : "PLACES",
    "pregnancy" : "PREGNANCY",
    "pregnancy complications" : "PREGNANCY",
    "pregnancy complications, infectious" : "PREGNANCY",
    "pregnancy outcome" : "PREGNANCY",
    "prenatal care" : "PREGNANCY",
    "prenatal diagnosis" : "PREGNANCY",
    "abortion, spontaneous" : "PREGNANCY",
    "fetal death" : "PREGNANCY",
    "fetal diseases" : "PREGNANCY",
    "fetus" : "PREGNANCY",
    "maternal-fetal exchange" : "PREGNANCY",
    "mothers" : "PREGNANCY",
    "bipolar disorder" : "PSYCHOLOGY",
    "psychology" : "PSYCHOLOGY",
    "psychotic disorders" : "PSYCHOLOGY",
    "schizophrenia" : "PSYCHOLOGY",
    "dementia" : "PSYCHOLOGY",
    "reproducibility of results" : "RESEARCH",
    "research" : "RESEARCH",
    "standards" : "RESEARCH",
    "statistics & numerical data" : "RESEARCH",
    "statistics as topic" : "RESEARCH",
    "terminology as topic" : "RESEARCH",
    "trends" : "RESEARCH",
    "cohort studies" : "RESEARCH",
    "cost-benefit analysis" : "RESEARCH",
    "costs and cost analysis" : "RESEARCH",
    "cross-sectional studies" : "RESEARCH",
    "data collection" : "RESEARCH",
    "evaluation studies as topic" : "RESEARCH",
    "follow-up studies" : "RESEARCH",
    "informed consent" : "RESEARCH",
    "methods" : "RESEARCH",
    "prospective studies" : "RESEARCH",
    "report" : "RESEARCH",
    "retrospective studies" : "RESEARCH",
    "surveys and questionnaires" : "RESEARCH",
    "analysis" : "RESEARCH",
    "classification" : "RESEARCH",
    "risk" : "RISK",
    "risk assessment" : "RISK",
    "risk factors" : "RISK",
    "serologic tests" : "SERUM",
    "serum" : "SERUM",
    "syphilis serodiagnosis" : "SERUM",
    "immune sera" : "SERUM",
    "" : "SEX",
    "sex factors" : "SEX",
    "sexual behavior" : "SEX",
    "sexual partners" : "SEX",
    "sexually transmitted diseases" : "SEX",
    "skin" : "SKIN",
    "skin diseases" : "SKIN",
    "skin diseases, infectious" : "SKIN",
    "skin neoplasms" : "SKIN",
    "skin tests" : "SKIN",
    "skin ulcer" : "SKIN",
    "syphilis, cutaneous" : "SKIN",
    "dermatitis" : "SKIN",
    "dermatology" : "SKIN",
    "facial dermatoses" : "SKIN",
    "hand dermatoses" : "SKIN",
    "leprosy" : "SKIN",
    "spinal cord" : "SPINE",
    "spinal cord diseases" : "SPINE",
    "spinal diseases" : "SPINE",
    "spinal puncture" : "SPINE",
    "spirochaeta" : "SPIROCHAETA",
    "spirochaetales" : "SPIROCHAETA",
    "spirochaetales infections" : "SPIROCHAETA",
    "stomach" : "STOMACH",
    "stomach diseases" : "STOMACH",
    "stomach neoplasms" : "STOMACH",
    "syphilis" : "SYPHILLIS",
    "syphilis, congenital" : "SYPHILLIS",
    "syphilis, latent" : "SYPHILLIS",
    "treponema" : "TREPONEMA",
    "treponema immobilization test" : "TREPONEMA",
    "treponema pallidum" : "TREPONEMA",
    "treponemal infections" : "TREPONEMA",
    "trichomonas infections" : "TRICHOMONAS",
    "trichomonas vaginalis" : "TRICHOMONAS",
    "trichomonas vaginitis" : "TRICHOMONAS",
    "biomedical research" : "TRICHOMONAS",
    "tuberculosis" : "TUBERCULOSIS",
    "tuberculosis, cutaneous" : "TUBERCULOSIS",
    "tuberculosis, meningeal" : "TUBERCULOSIS",
    "tuberculosis, pulmonary" : "TUBERCULOSIS",
}
